apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newmu-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: newmu.local
    http:
      paths:
      - path: /mu-app
        pathType: Prefix
        backend:
          service:
            name: mu-service
            port:
              number: 80
  - host: 403-error.com
    http:
      paths:
      - path: /mu-app
        pathType: Prefix
        backend:
          service:
            name: mu-service
            port:
              number: 80

