# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mu-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mu-app
  template:
    metadata:
      labels:
        app: mu-app
    spec:
      containers:
      - name: mu-app
        image: mu-app:v1.0
        ports:
        - containerPort: 80
