apiVersion: v1
kind: Service
metadata:
  name: mu-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80               # External port for the service
    targetPort: 80         # The container port your app listens on
    protocol: TCP          # Protocol used by the service
    nodePort: 32700        # Fixed NodePort for fallback access
  selector:
    app: mu-app            # Matches the 'app' label in your Deployment
