apiVersion: v1
kind: Service
metadata:
  name: mu-service
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32700  # Specify nodePort here
  selector:
    app: mu-app
