apiVersion: v1
kind: Service
metadata:
  name: new-service
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32701  # Specify nodePort here
  selector:
    app: new-app
