apiVersion: v1
kind: Service
metadata:
  name: new-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80               # The port your service exposes externally
    targetPort: 80      # The container port your app listens on
    protocol: TCP          # Use TCP for HTTP traffic
    nodePort: 32701        # Optional: Fixed NodePort (still accessible for debugging)
  selector:
    app: new-app           # Matches the 'app' label in your Deployment
