apiVersion: v1
kind: Service
metadata:
  name: new-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    nodePort: 32701
  selector:
    app: new-app
